// <auto-generated />
using BusinessLogic.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 15,
                            AttackModifier = 0,
                            AttackPerRound = 1,
                            Damage = "2d6",
                            DamageModifier = -1,
                            HitPoints = 7,
                            Name = "Гоблин"
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 8,
                            AttackModifier = 9,
                            AttackPerRound = 1,
                            Damage = "3d8",
                            DamageModifier = 1,
                            HitPoints = 22,
                            Name = "Зомби"
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 11,
                            AttackModifier = 1,
                            AttackPerRound = 1,
                            Damage = "1d8",
                            DamageModifier = 0,
                            HitPoints = 5,
                            Name = "Гиена"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
